# Generated by Django 5.2.3 on 2025-07-12 02:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_database_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visitrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='visitlog',
            new_name='core_visitl_visit_r_7f7fc4_idx',
            old_name='core_visitlog_visit_request_idx',
        ),
        migrations.RenameIndex(
            model_name='visitlog',
            new_name='core_visitl_visitor_4d02be_idx',
            old_name='core_visitlog_visitor_idx',
        ),
        migrations.RenameIndex(
            model_name='visitlog',
            new_name='core_visitl_check_i_cbef8b_idx',
            old_name='core_visitlog_check_in_time_idx',
        ),
        migrations.RenameIndex(
            model_name='visitlog',
            new_name='core_visitl_check_o_fbf400_idx',
            old_name='core_visitlog_check_out_time_idx',
        ),
        migrations.RenameIndex(
            model_name='visitlog',
            new_name='core_visitl_checked_e31dd8_idx',
            old_name='core_visitlog_checked_in_by_idx',
        ),
        migrations.RenameIndex(
            model_name='visitlog',
            new_name='core_visitl_created_57350e_idx',
            old_name='core_visitlog_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='visitor',
            new_name='core_visito_email_4b1d47_idx',
            old_name='core_visitor_email_idx',
        ),
        migrations.RenameIndex(
            model_name='visitor',
            new_name='core_visito_full_na_e17917_idx',
            old_name='core_visitor_full_name_idx',
        ),
        migrations.RenameIndex(
            model_name='visitor',
            new_name='core_visito_created_568fc0_idx',
            old_name='core_visitor_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='visitrequest',
            new_name='core_visitr_employe_8ea4d0_idx',
            old_name='core_visitrequest_employee_status_idx',
        ),
        migrations.RenameIndex(
            model_name='visitrequest',
            new_name='core_visitr_employe_3c08c0_idx',
            old_name='core_visitrequest_employee_scheduled_time_idx',
        ),
        migrations.RenameIndex(
            model_name='visitrequest',
            new_name='core_visitr_status_ac000a_idx',
            old_name='core_visitrequest_status_scheduled_time_idx',
        ),
        migrations.RenameIndex(
            model_name='visitrequest',
            new_name='core_visitr_visitor_504857_idx',
            old_name='core_visitrequest_visitor_status_idx',
        ),
        migrations.RenameIndex(
            model_name='visitrequest',
            new_name='core_visitr_schedul_d86d0f_idx',
            old_name='core_visitrequest_scheduled_time_status_idx',
        ),
        migrations.RenameIndex(
            model_name='visitrequest',
            new_name='core_visitr_created_0e9203_idx',
            old_name='core_visitrequest_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='visitrequest',
            new_name='core_visitr_token_808545_idx',
            old_name='core_visitrequest_token_idx',
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='original_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='check_in_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='check_out_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='full_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='scheduled_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('no_show', 'No Show'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='visit_type',
            field=models.CharField(choices=[('scheduled', 'Pre-Approved'), ('walkin', 'Walk-In')], db_index=True, default='scheduled', max_length=10),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['original_employee', 'status'], name='core_visitr_origina_5c49d7_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['original_employee', 'scheduled_time'], name='core_visitr_origina_042bc0_idx'),
        ),
    ]
